name: Prevent Direct Push to Master

on:
  push:
    branches:
      - master

jobs:
  prevent_push_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Check for direct push to master
        run: |
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            echo "Direct push to master is not allowed."
            exit 1
          fi
